#!/bin/bash
rm -Rf packages
javapackager -deploy -native $1 -outdir packages -outfile augustmc \
    -srcfiles augustmc*.jar -appclass com.simontuffs.onejar.Boot \
    -name "AugustMC" -title "August MC 2017.1" -v -BappVersion=2017.1

