#!/bin/bash

jar=$(ls augustmc-*.jar)

if [ -z $jar ]; then
  echo "No jar found"
  exit 0
fi

version=${jar#"augustmc-"}
version=${version%".jar"}

echo "version: $version"
rm -Rf packages
javapackager -deploy -native $1 -outdir packages -outfile augustmc \
    -srcfiles $jar -appclass com.simontuffs.onejar.Boot \
    -name "AugustMC" -title "August MC $version" -v -BappVersion=$version

